---
- find: path={{ SGE_ROOT }}/default/common/install_logs/ file_type=file
  register: files
  
- find: path={{ SGE_ROOT }}/default/common/install_logs/ file_type=directory
  register: directories

- name: clear install log
  become: yes
  file: state=absent path={{item.path}}
  with_items: 
    - path: "{{ files }}"
    - path: "{{ directories }}"

- name: remove RC scripts
  become: yes
  file: path=/etc/init.d/sgeexecd.cluster state=absent

- name: install exection host
  become: yes
  command: "cd {{ SGE_ROOT }} && ./inst_sge -x -noremote -auto util/install_modules/sge_configuration.conf"
  register: install_sge

- debug: msg="install sge:{{ install_sge.stdout_lines }}"
