---
- name: transform ecs input 
  hosts: all
  vars_files:
     - default.yml
  tasks:
     - template: >
        src=templates/ecs.j2
        dest=~/app/ecs.json

- name: instance show
  hosts: all
  vars_files:
     - default.yml
  tasks:
     - shell: ". venv/bin/activate && aliyuncli ecs DescribeInstances"
       args:
         chdir: "~"
         executable: /bin/bash
       register: json_response
     - file: path="~/instances.txt" state=absent
     - shell: "echo {{ item.InstanceName }} >> ~/instances.txt"
       with_items: "{{ (json_response.stdout | from_json)['Instances']['Instance'] }}"
       no_log: True
     - shell: "cat ~/instances.txt"
       register: instances
     - debug: msg="{{ instances.stdout_lines }}"
