---
- name: instance delete by name
  hosts: all
  vars_files:
     - default.yml
  tasks:
     - shell: ". venv/bin/activate && aliyuncli ecs DescribeInstances --InstanceName {{ HostName }}"
       args:
         chdir: "~"
         executable: /bin/bash
       register: json_response
     - set_fact: InstanceId="{{ (json_response.stdout | from_json)['Instances']['Instance'][0]['InstanceId'] }}"
     - debug: msg="{{ InstanceId }}"
     - shell: ". venv/bin/activate && aliyuncli ecs AllocateEipAddress"
       args:
         chdir: "~"
         executable: /bin/bash
       register: json_response
     - set_fact: EIP="public EIP:{{ (json_response.stdout | from_json)['EipAddress'] }}"
     - set_fact: AllocationId="{{ (json_response.stdout | from_json)['AllocationId'] }}"
     - debug: msg="{{ (json_response.stdout | from_json) }}"
     - shell: ". venv/bin/activate && aliyuncli ecs AssociateEipAddress --InstanceId {{ InstanceId }} --AllocationId {{ AllocationId }}"
       args:
         chdir: "~"
         executable: /bin/bash
       register: json_response
     - debug: msg="{{ (json_response.stdout | from_json) }}"
