---
- name: instance delete by name
  hosts: all
  vars_files:
     - default.yml
  tasks:
     - shell: ". venv/bin/activate && aliyuncli ecs DescribeInstances --InstanceName {{ HostName }}"
       args:
         chdir: "~"
         executable: /bin/bash
       register: json_response
     - set_fact: InstanceId="{{ (json_response.stdout | from_json)['Instances']['Instance'][0]['InstanceId'] }}"
     - debug: msg="{{ InstanceId }}"
     - shell: ". venv/bin/activate && aliyuncli ecs ReplaceSystemDisk --InstanceId {{ InstanceId }} --ImageId {{ ImageId }} --Bandwidth"
       args:
         chdir: "~"
         executable: /bin/bash
       register: json_response
     
     - debug: msg="{{ (json_response.stdout | from_json) }}"
