---
- name: creating {{ user }} group
  hosts: all
  sudo: yes
  remote_user: "{{ remote_user }}"
  vars_files:
     - default.yml
  tasks:
    - group: name={{ group }} state=present

- name: creating {{ user }} user
  hosts: all
  vars_files:
     - default.yml
  remote_user: "{{ remote_user }}"
  sudo: yes
  tasks:
    - user: name={{ user }} group={{ group }} groups="sudo,{{ group}}" password={{ passwd }} shell=/bin/bash state=present
    - file: path=/home/{{ user }}/.ssh/ssl state=directory
