---
- name: change host name
  hosts: all
  sudo: yes
  vars_files:
     - default.yml
  tasks:
    - hostname: name={{ hostname }}

- name: creating {{ user }} group
  hosts: all
  sudo: yes
  remote_user: "{{ remote_user }}"
  vars_files:
     - default.yml
  tasks:
    - group: name={{ group }} state=present

- name: creating {{ user }} user
  hosts: all
  vars_files:
     - default.yml
  remote_user: "{{ remote_user }}"
  sudo: yes
  tasks:
    - user: name={{ user }} group={{ group }} groups="root,{{ group}}" password={{ passwd }} shell=/bin/bash state=present
    - file: path=/home/{{ user }}/.ssh/ssl state=directory

- name: passwdless sudo
  hosts: all
  vars_files:
     - default.yml
  remote_user: "{{ remote_user }}"
  sudo: yes
  tasks: 
    - file: path=/etc/sudoers.d/{{ user }} state=touch mode="0440" owner=root group=root
    - lineinfile: dest=/etc/sudoers.d/{{ user }} 
                  line="{{ user }} ALL = (root) NOPASSWD:ALL"
