---
- name: install sshpass on ansible host
  hosts: localhost
  tasks: 
    - apt: name={{ item }} state=present
      with_items:
        - sshpass

- name: add SSH authorized key
  hosts: all
  sudo: yes
  tasks:
    - authorized_key:
        user={{ansible_ssh_user}}
        key="{{ lookup('file', '~/.ssh/rsa_key_pair_1.pub') }}"
