---
- hosts: k8s:k8s1:k8s2
  sudo: yes
  roles:
    - ~/galaxy/angstwad.docker_ubuntu
  post_tasks:
    - apt: name=bridge-utils state=present
    - lineinfile: dest=/etc/default/docker
                  line="export http_proxy="http://proxy.houston.hpecorp.net:8080""
    - service: name=docker state=restarted
