---
#www.yml : playbook for web servers
- hosts: k8s
  remote_user: ubuntu
  roles:
     - role: kuber
       knodes: ubuntu@8.0.0.16 ubuntu@8.0.0.18 ubuntu@8.0.0.19
       no_proxy: localhost,127.0.0.1,8.0.0.0/24
