---
#www.yml : playbook for web servers
- hosts: k8s
  remote_user: ubuntu
  roles:
     - role: kuber
       knodes: ubuntu@8.0.0.16
       is_proxy: true 
       proxy: http_proxy=http://proxy.houston.hpecorp.net:8080 https_proxy=http://proxy.houston.hpecorp.net:8080
