---
#www.yml : playbook for web servers
- hosts: all
  remote_user: ubuntu
  become: yes
  pre_tasks:
     - shell: echo 'I":" Beginning to set gateway..'
  roles:
     - kuber
  post_tasks:
     - shell: echo 'I":" Done'
