---
#- name: create openrc
#  template: src=openrc.j2 dest=~/{{ name }}/openrc mode=0644
  
- name: set user info
  template: src=add-instance-redo.j2 dest=~/{{ name }}/add-instance-redo.sh mode=0744
  
  
- name: display service url
  command: cat ~/service.osrc
  register: service

- name: display 
  debug: msg={{ service.stdout_lines }}
  
- name: execute script to add network
  command: /home/stack/{{ name }}/add-instance-redo.sh
