---
#- name: create openrc
#  template: src=openrc.j2 dest=~/{{ name }}/openrc mode=0644
  
- name: set user info
  template: src=add-instance-redo.j2 dest=~/{{ name }}/add-instance-redo.sh mode=0744
  
- name: execute script to add network
  command: /home/stack/{{ name }}/add-instance-redo.sh
