---
#www.yml : playbook for web servers
- hosts: gate
  remote_user: ubuntu
  sudo: yes
  pre_tasks:
     - shell: echo 'I":" Beginning to install keystone..'
  roles:
     - keystone
  post_tasks:
     - shell: echo 'I":" Done'
