---
# essential tasks. should run on all nodes
- name: install deployer
  become: yes
  pip: name=ceph-deploy
  
- name: mkdir /etc/ceph
  become: yes
  file: path=/etc/ceph state=directory
 
- name: create deployer script
  template: src=deployer.j2 dest=~/deployer.sh mode=0744

  

  



