home: whg
name: whg1
admin_name: adm_whg1
user_name: whg1
password: 123
pub_key: rsa_key_pair_1.pub 
router: router_whg1_21
net_name: net_whg1_8
sub_net: 8.0.0.0/24 
net_name_2: net_whg1_29
sub_net_2: 29.0.0.0/24
external_network: ext-net
security_group: sec-whg
image_name: cirros-0.3.4-x86_64
image_name_2: cirros-0.3.3-x86_64
flavor: m1.small
resource_id: nova_instance_id
