---
- name: start execd service
  become: yes
  command: chkconfig  sgeexecd.cluster on && /etc/init.d/sgeexecd.cluster start

- name: modify exec server template
  become: yes
  lineinfile:
    dest: "{{ SGE_ROOT }}/execd.txt"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^complex_values', line: 'complex_values     virtual_free={{ virtual_free }},num_proc={{ num_proc }}' }
    - { regexp: '^hostname', line: 'hostname     {{ execd_name }}.local' }
    - { regexp: '^load_values.*$', line: '' }
    - { regexp: '^processors.*$', line: '' }
    - { regexp: 'swap_total=.*$', line: '' }
    - { regexp: 'mem_used=.*$', line: '' }
    - { regexp: 'virtual_used=.*$', line: '' }
    - { regexp: 'm_topology_inuse=.*$', line: '' }
    - { regexp: 'np_load_avg=.*$', line: '' }
    - { regexp: 'np_load_medium=.*$', line: '' }

- name: modify exec server
  become: yes
  command: "cd {{ SGE_ROOT }} && {{ SGE_ROOT }}/bin/linux-x64/qconf -Me execd.txt"
