---
# essential tasks. should run on all nodes
- name: install git
  apt: name=git state=present

- name: clone kubernetes source
  git: repo=https://github.com/kubernetes/kubernetes.git
       dest=/home/{{ ansible_ssh_user }}/kubernetes
       update=no

- name: Set cluser node parameters
  lineinfile:
    dest: /home/{{ ansible_ssh_user }}/kubernetes/cluster/ubuntu/config-default.sh
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^export nodes=', line: 'export nodes=${nodes:-"{{ knodes }}"}' }

- name: Set cluser provider
  lineinfile: dest=/home/{{ ansible_ssh_user }}/.bashrc
              line="{{ item }}"
  with_items:
    - export KUBE_VERSION=1.0.5
    - export KUBERNETES_PROVIDER=ubuntu
    - export FLANNEL_VERSION=0.5.0
    - export ETCD_VERSION=2.2.0

