---
# essential tasks. should run on all nodes
- name: Add the new gpg key
  become: yes
  apt_key: url=hkp://p80.pool.sks-keyservers.net:80
           id=58118E89F3A912897C070ADBF76221572C52609D
           state=present
  
- name: create docker apt source
  become: yes
  file: name=/etc/apt/sources.list.d/docker.list state=present

- name: add docker source entry
  become: yes
  lineinfile: dest=/etc/apt/sources.list.d/docker.list
              line={{ item }}
  with_items:
    - deb https://apt.dockerproject.org/repo ubuntu-trusty main

- name: update chate
  apt: update_cache=yes

- name: remove lxc-docker  
  become: yes
  apt: name=lxc-docker state=absent

- name: install docker
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - docker-engine
    - bridge-utils
  lineinfile: dest=/etc/default/docker
              line="export http_proxy={{ http_proxy }}"
  service: name=docker state=restarted
  

- name: creating docker group
  become: yes
  group: name=docker state=present
  
- name: add user to docker group
  become: yes
  user: name={{ ansible_env.SUDO_USER }} group=docker state=present
  
- name: Adjust memory and swap
  become: yes
  lineinfile: dest=/etc/default/grub
              line="GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1""
  command: update-grub
  
- name: Adjust ufw
  become: yes
  lineinfile: dest=/etc/default/ufw
              line="DEFAULT_FORWARD_POLICY="ACCEPT""
  command: 
    - ufw reload
    - ufw allow 2375/tcp
  
- name: install git
  apt: name=git state=present

