---
- name: creating {{ group }} group
  hosts: all
  sudo: yes
  vars_files:
     - default.yml
  tasks:
    - group: name={{ group }} state=present

- name: creating {{ user }} user
  hosts: all
  sudo: yes
  vars_files:
     - default.yml
  tasks:
    - user: name={{ user }} group={{ user }} state=present
    - file: path=/home/{{ user }}/.ssh/ssl state=directory

- name: add ipc key to ceph
  hosts: all
  sudo: True
  vars_files:
     - default.yml
  tasks:
    - command: cp ~/.ssh/authorized_keys /home/{{ user }}/.ssh/authorized_keys
