---
- name: install ansible
  sudo: yes
  hosts: k8s1
  tasks:
    - apt: name=software-properties-common
    - apt_repository: repo='ppa:ansible/ansible'
    - apt: update_cache=yes
    - apt: name=ansible


- name: copy config
  hosts: ansi
  tasks:
    - copy: src=~/.ansible.cfg dest=~/.ansible.cfg
    - copy: src=~/.ssh/config dest=~/.ssh/config
