---
- name: install ansible
  sudo: yes
  hosts: all 
  tasks:
    #- apt: name=software-properties-common
    #- apt_repository: repo='ppa:ansible/ansible'
    #- apt: update_cache=yes
    #- apt: name=ansible

- name: install ansible from source
  hosts: all
  tasks:
    - git: repo=https://github.com/ansible/ansible.git
           dest=/home/{{ ansible_ssh_user }}/ansible
    - lineinfile: dest=/home/{{ ansible_ssh_user }}/.bashrc 
                  line="export PATH=/home/{{ ansible_ssh_user }}/ansible/bin/:$PATH
    


- name: copy config
  hosts: all
  tasks:
    - command: python setup.py install
    - copy: src=~/.ansible.cfg dest=~/.ansible.cfg
    - copy: src=~/.ssh/config dest=~/.ssh/config
    - copy: src=~/.ssh/git_hub_id_rsa dest=~/.ssh/git_hub_id_rsa
    - tags: git_hub
