---
- name: update python to 2.7.11
  sudo: yes
  hosts: k8s1
  tasks:
    #- command: apt-add-repository ppa:fkrull/deadsnakes-python2.7
    - apt_repository: repo='ppa:fkrull/deadsnakes-python2.7'
    - apt: update_cache=yes
    - apt: name=python2.7 state=latest
