---
- name: upload pub key
  copy: src=~/.ssh/rsa_key_pair_1.pub dest=~/{{ name }}/rsa_key_pair_1.pub state=present
  
- name: set user info
  template: src=add-instance.j2 dest=~/{{ name }}/add-instance.sh mode=0744
  
- name: execute script to add network
  command: /home/stack/{{ name }}/add-instance.sh
