---
- name: upload pub key
  copy: src=~/.ssh/{{ pub_key }} dest=~/{{ home }}/{{ pub_key }}
        validate='ls -l %s'
  
- name: set user info
  template: src=add-instance.j2 dest=~/{{ home }}/add-instance.sh mode=0744
  
- name: execute script to add network
  command: /home/stack/{{ home }}/add-instance.sh
