---
- name: create hadoop group
  become: yes
  group: name=hadoop state=present

- name: create user yarn
  become: yes
  user: name=yarn group=hadoop
  
- name: create user yarn
  become: yes
  user: name=hdfs group=hadoop

- name: create user mapred
  become: yes
  user: name=mapred group=hadoop

