---
- name: create hadoop group
  become: yes
  group: name=hadoop state=present

- name: create user yarn
  become: yes
  user: name=yarn group=hadoop
  
- name: create user hdfs
  become: yes
  user: name=hdfs group=hadoop

- name: create user mapred
  become: yes
  user: name=mapred group=hadoop  
  
- name: create hdfs directory
  become: yes
  file: path=/var/data/hadoop/hdfs  owner=hdfs group=hadoop state=directory

- name: create hdfs nn directory
  become: yes
  file: path=/var/data/hadoop/hdfs/nn  owner=hdfs group=hadoop state=directory


- name: create hdfs  snn directory
  become: yes
  file: path=/var/data/hadoop/hdfs/snn  owner=hdfs group=hadoop state=directory


- name: create hdfs dn directory
  become: yes
  file: path=/var/data/hadoop/hdfs/dn  owner=hdfs group=hadoop state=directory 
  
- name: create log yarn directory
  become: yes
  file: path=/var/log/hadoop/yarn  owner=yarn group=hadoop state=directory
  
- name: set hostname
  become: yes
  lineinfile:  dest=/etc/hosts line="{{ ansible_eth0.ipv4.address }} {{ ansible_hostname }}"  

- name: download hadoop
  become: yes
  get_url: url=http://apache.osuosl.org/hadoop/common/stable/hadoop-2.7.2.tar.gz dest=/opt/hadoop-2.7.2.tar.gz mode=0776
  
- name: untar hadoop
  become: yes
  command: tar zxf /opt/hadoop-2.7.2.tar.gz -C /opt
  # unarchive: src=/opt/hadoop-2.7.2.tar.gz dest=/opt    

- name: create install log
  become: yes
  file: path={{ yarn_home }}/logs  owner=yarn group=hadoop state=directory mode="u=rw,g=rw,o=r"